In [1]:
from pvt_model import pvt_model
import numpy as np

1. Объявление модели

In [2]:
model = pvt_model(0.5, 0.9, 1, 100, 0.8)

2.1 Расчет pvt свойств в одной точке

In [3]:
model.calc_pvt(29997500, 320)

[array([1.00567871]),
 array([994.3533578]),
 array([0.65570927]),
 array([4186.787]),
 array([1363.14824811]),
 array([0.92935827]),
 array([0.00347939]),
 array([173.15736181]),
 array([0.02158147]),
 array([3747.55710066]),
 array([25698770.76030537]),
 array([100.]),
 array([1.03814781e-09]),
 array([1.22864723]),
 array([782.23022276]),
 array([2.23447162]),
 array([1972.3195]),
 array([0.05706546]),
 array([0.00504763]),
 array([3.89710501e-10])]

In [5]:
rsb = 100.0
t = 320
gamma_gas = 0.5
gamma_oil = 0.9
p = 30000000
(28.073 * rsb + 30.96 * (t - 273) - 1180 * gamma_gas + 1784.315 / gamma_oil - 2540.8) / (100000 * p)

1.038064074074074e-09

In [13]:
model.rho_oil

886.8400587350405

In [14]:
model.muo

33.482453367952104

2.2 Расчет pvt свойств в одной точке (при передаче списка параметров, метод возвращает перечисленные свойства)

In [15]:
model.calc_pvt(5*10**5, 310, ['rho_oil', 'muo'])

[array([886.84005874]), array([33.48245337])]

2.3 Расчет pvt свойств в нескольких точках (при передаче списка параметров, метод возвращает перечисленные свойства)

In [16]:
p = np.array([2*10**5, 3*10**5, 5*10**5], dtype=float)
t = np.array([290, 295, 310], dtype=float)

In [17]:
model.calc_pvt(p, t, ['rho_oil', 'muo'])

[array([902.85916681, 898.88738522, 886.84005874]),
 array([397.94324151, 177.87618819,  33.48245337])]

2.4 Расчет pvt свойств в нескольких точках с использованием тензеров (при передаче списка параметров, метод возвращает перечисленные свойства)

In [18]:
import torch

In [19]:
model.calc_pvt(torch.tensor(p, requires_grad=True), torch.tensor(t, requires_grad=True), ['rho_oil', 'muo'])

[tensor([902.8592, 898.8874, 886.8401]),
 tensor([397.9432, 177.8762,  33.4825])]